# Create a self-signed Issuer for the root CA
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "libdns-webhook.selfSignedIssuer" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "libdns-webhook.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
# Generate a CA Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "libdns-webhook.caCertificate" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "libdns-webhook.labels" . | nindent 4 }}
spec:
  secretName: {{ include "libdns-webhook.caCertificate" . }}
  duration: 43800h # 5 years
  issuerRef:
    name: {{ include "libdns-webhook.selfSignedIssuer" . }}
  commonName: "ca.libdns-webhook.cert-manager"
  isCA: true
---
# Create an Issuer using the CA
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "libdns-webhook.caIssuer" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "libdns-webhook.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "libdns-webhook.caCertificate" . }}
---
# Generate a serving certificate for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "libdns-webhook.servingCertificate" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "libdns-webhook.labels" . | nindent 4 }}
spec:
  secretName: {{ include "libdns-webhook.servingCertificate" . }}
  duration: 8760h # 1 year
  issuerRef:
    name: {{ include "libdns-webhook.caIssuer" . }}
  dnsNames:
    - {{ include "libdns-webhook.fullname" . }}
    - {{ include "libdns-webhook.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "libdns-webhook.fullname" . }}.{{ .Release.Namespace }}.svc
